services:
  comments:
    image: ghcr.io/byandrev/hilo:latest
    ports: ["8000:8000"]
    env_file: .env
    environment:
      MONGO_URI: mongodb://mongo:27017
    depends_on: [mongo]
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes: ["./data:/data/db"]
    restart: unless-stopped
